package com.wlf.index.application.mapper;

import com.wlf.index.application.entity.Choices;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface ChoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbg.generated
     */
    int insert(Choices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbg.generated
     */
    Choices selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbg.generated
     */
    List<Choices> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Choices record);
}