package com.wlf.index.application.mapper;

import com.wlf.index.application.entity.SliderImg;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SliderImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slider_img
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slider_img
     *
     * @mbg.generated
     */
    int insert(SliderImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slider_img
     *
     * @mbg.generated
     */
    SliderImg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slider_img
     *
     * @mbg.generated
     */
    List<SliderImg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slider_img
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SliderImg record);
}