package com.wlf.index.application.mapper;


import com.wlf.index.application.entity.ThemeImg;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface ThemeImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme_img
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme_img
     *
     * @mbg.generated
     */
    int insert(ThemeImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme_img
     *
     * @mbg.generated
     */
    ThemeImg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme_img
     *
     * @mbg.generated
     */
    List<ThemeImg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme_img
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ThemeImg record);
}