package com.wlf.index.application.entity;

import java.io.Serializable;

public class ThemeImg implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theme_img.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theme_img.smallpic
     *
     * @mbg.generated
     */
    private String smallpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table theme_img
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theme_img.id
     *
     * @return the value of theme_img.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theme_img.id
     *
     * @param id the value for theme_img.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theme_img.smallpic
     *
     * @return the value of theme_img.smallpic
     *
     * @mbg.generated
     */
    public String getSmallpic() {
        return smallpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theme_img.smallpic
     *
     * @param smallpic the value for theme_img.smallpic
     *
     * @mbg.generated
     */
    public void setSmallpic(String smallpic) {
        this.smallpic = smallpic == null ? null : smallpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme_img
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", smallpic=").append(smallpic);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}